var json_PN_7 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Nom du lie": "Feux Alimentation Surface", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.49378062, 12.37605682 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Échangeur de l'Est", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.47225284, 12.39219947 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de Kossodo", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.50002475, 12.39347097 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux CP-Ouaga 2000", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.5027341, 12.3178461 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Marché du bétail(Tanghin)", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.5352644, 12.39211048 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point Shiphra", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51668348, 12.39003242 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux du camp paspanga", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51521532, 12.38211321 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de ISIG", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.49800671, 12.36116276 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point du 1200 logements", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.49532789, 12.35901833 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de Boinse Yaare", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.50666871, 12.36822747 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux affaires étrangères", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.50692813, 12.3702795 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux SONAPOST Sig-Noghin", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.55791686, 12.38728619 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux TOECIN YAAR", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.57940324, 12.38995078 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Marché de bétail", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.58295849, 12.39017742 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "SOGELB Kilwin", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.58711613, 12.39013964 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Fin des deux voies Bar du maire Kilwin", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.59095289, 12.39014783 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux tricolore Bissinghin", "Nom de l��": "Police nationale, BJVSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5996047, 12.3906239 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Bretelle Bissinghin-Bassinko", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.63794557, 12.4165549 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Carrefour Yagma", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.62327947, 12.40394796 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de l'Olympisme(ENP)", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54513063, 12.36769112 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Total Kadiogo", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53857094, 12.36193328 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Place du 2 octobre", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53117327, 12.36765486 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux BCEAO", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52864195, 12.3683511 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point des Cinéastes", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52739972, 12.36882253 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Grand Lion", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52658658, 12.36982965 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Telmob", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52482014, 12.37033816 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux SOBCA", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52172493, 12.37090571 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point des Nations Unies", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52030168, 12.37127915 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "STOP Commissariat Central de la Police de Ouagadougou", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51917102, 12.36836982 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux DGTTM", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51914136, 12.36880833 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Ciné Burkina", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52140362, 12.369263 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Loudin", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52121163, 12.36677602 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux hôtel Palm Beach annexe", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52075246, 12.36446931 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux U.A.B", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52177279, 12.36455814 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Saint Exupéry", "Nom de l��": "Police nationale, BJVSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52482319, 12.36382786 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Cathédrale(Porte Nord)", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52641499, 12.36372294 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Camp Fonctionnaire", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5285942, 12.36319933 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Marché Cité An II", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52726285, 12.35660966 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Jardin de l'Unité Africaine", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52662279, 12.34700153 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Château d'eau Mogho Naaba", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52706557, 12.35589179 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Porte Cathédrale", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52767346, 12.36213989 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux BCB", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51722203, 12.35749612 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Croisement fonction publique (Kwame Nkrumah)", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51804752, 12.36310007 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux DGPN", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51656668, 12.37203186 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux RTB", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.51010317, 12.37393311 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point du Coq", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.50821277, 12.37389804 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Lycée Nelson", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.51549079, 12.3748821 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Lycée Zinda", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.51721071, 12.37355621 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Assemblée de Dieu", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52236762, 12.37335318 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux École Nationale des Douanes", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5207409, 12.37467844 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Cité An III", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53252832, 12.37769561 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Bon Samaritain", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53950505, 12.37814382 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Total Kolog-Naaba", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54654463, 12.37841324 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Le Bakin", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55475091, 12.40496681 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Route Kongoussi station Shell", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.55183419, 12.42107088 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Télévision BF1", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.50289365, 12.30585788 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Camp de l'Unité", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.56274697, 12.34762571 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Petrofa Ouaga 2000", "Nom de l��": "Police nationale, ABSER", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52864899, 12.3174203 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Hôtel Palace", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52877601, 12.30613958 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux IAM", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.50258062, 12.32729327 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Route Pô(station Total )", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.48623398, 12.31467712 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Échangeur route de Pô", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.49846064, 12.32878975 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Résidence Alice", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.49911021, 12.33545801 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Pédiatrie Charles De Gaules", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.47223272, 12.3756893 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux présidence de l'Université", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.50415224, 12.37484846 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Place Naaba Kom", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52600023, 12.37257912 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Watam Kaizer", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.53894704, 12.3557188 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Marché Théâtre Populaire", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.53519834, 12.3556779 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Lycée Saint Joseph", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52631726, 12.33978436 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux de l'ASECNA", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52423, 12.34769223 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Barrière Aéroport", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.51636124, 12.35369842 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "TCV", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.52026663, 12.35683576 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point des Droits humains", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.51439453, 12.32763918 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Jardin Ouaga 2000", "Nom de l��": "Police nationale", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52724626, 12.3274073 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Château d'eau Quatre Yaar", "Nom de l��": "Police nationale", "Present": "NON" }, "geometry": { "type": "Point", "coordinates": [ -1.48015005, 12.35024317 ] } }
]
}
