var json_VADS_6 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Nom du lie": "Lycée Wend Manegda", "Nom de l��": "VADS, BJVSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55470892, 12.35085952 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux OTAM 1200 logements", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.49410253, 12.36873207 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Marché de Bendogo", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.45634542, 12.39608333 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Silmande", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.47762829, 12.41363376 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Carrefour de la boulangerie Wend Konta", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.4881574, 12.40495675 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de Shiphra", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51657774, 12.38999095 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux de saint Camille", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.49799441, 12.36855236 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux de la rue 30.81", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.49005195, 12.35601563 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux de l'hôpital Yalgado", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.50919082, 12.37957728 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux du barrage de Tanguin", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5162552, 12.38716037 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux de Coris Bank Paul 6", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5560005, 12.39661332 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Ciné Tampoui", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5682783, 12.38847472 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux rail Gonghin", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55873332, 12.37025605 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Ex-CGP(Stade du 4 Août )", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55857971, 12.3630176 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "BICIA Gounghin", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54308273, 12.35960706 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point Bataille du rail", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53387071, 12.36495729 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Baskuy Yaar", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54984179, 12.38087962 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point Cité Azimo", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.56576706, 12.40046246 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Marché Gounghin", "Nom de l��": "Police nationale & VADS, ABSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54814087, 12.35637612 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Siège ONEA", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.57244844, 12.34279226 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Lycée Benajia", "Nom de l��": "VADS, ABSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55258668, 12.32315851 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Lycée Universalis", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.53512651, 12.31821539 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Ouaga Inter", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51979818, 12.33288785 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Rond point de la Patte d'Oie", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52520613, 12.3332347 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Petrofa Cissin", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54744752, 12.33839209 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Cimetière de Gounghin", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55394001, 12.34450913 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Échangeur de l'Ouest", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.5562513, 12.35190854 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Centre Baboanga", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51438627, 12.40242922 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Faso Parc", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.49818188, 12.39650101 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Hôtel Yamba", "Nom de l��": "Police nationale & VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.54190401, 12.37544366 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Lycee Mixte de Gounghin", "Nom de l��": "VADS, ABSER", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55034827, 12.3485363 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Boulgou Bar", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.51470832, 12.36560299 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux Marché Cité AN II", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.52628791, 12.34216957 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux en allant vers le SIAO", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.4781224, 12.36682742 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Groupe scolaire SOMDE de Sig-Nonguin(présence des VADS)", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.55432226, 12.40732783 ] } },
{ "type": "Feature", "properties": { "Nom du lie": "Feux du Lycée Municipal de Sig-Nonguin(présence des VADS)", "Nom de l��": "VADS", "Present": "OUI" }, "geometry": { "type": "Point", "coordinates": [ -1.56069831, 12.39550705 ] } }
]
}
